version: "3.9"
services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: songssam
      MYSQL_USER: app
      MYSQL_PASSWORD: app
    ports: ["3306:3306"]

  redis:
    image: redis:7
    ports: ["6379:6379"]
